# https://snapcraft.io/docs/create-a-new-snap
name: tauno-monitor # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '0.1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: Simple stand-alone serial port monitor # 79 char long summary
description: |
  Simple a stand-alone serial port monitor for the GNOME desktop.
  It aims to be beginner-friendly, small and easy to use.
  Not feature-rich and professional.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  tauno-monitor:
    command: bin/tauno-monitor
    extensions: [ gnome ]
    plugs:
      - raw-usb
      - serial-port
      - hardware-observe

parts:
  tauno-monitor:
    plugin: meson
    source-type: git
    source: https://github.com/taunoe/tauno-monitor
    parse-info: [ usr/share/appdata/art.taunoerik.TaunoMonitor.appdata.xml ]
    build-packages:
      - blueprint-compiler
      #- libgtk-4-dev
      #- meson
      #- python3-dev
      #- python3-pip  # Added to ensure pip is available
    meson-parameters:
      - --prefix=/snap/tauno-monitor/current/usr
    #stage-packages:
    #  - python3
    override-build: |
      snapcraftctl build
      pip3 install --target=$SNAPCRAFT_PART_INSTALL/ pyserial
    organize:
      "bin/tauno-monitor": "bin/tauno-monitor"

