name: tauno-monitor
base: core22
version: '0.1.2'
summary: Simple stand-alone serial port monitor
description: |
  Simple a stand-alone serial port monitor for the GNOME desktop.
  It aims to be beginner-friendly, small and easy to use.
  Not feature-rich and professional.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  tauno-monitor:
    extensions: [ gnome ]
    command: usr/bin/tauno-monitor
    desktop: usr/share/applications/art.taunoerik.tauno-monitor.desktop
    common-id: art.taunoerik.tauno-monitor
    plugs:
      - home
      - raw-usb
      - serial-port
      #- hardware-observe

parts:
  tauno-monitor:
    plugin: meson
    source: .
    parse-info: [ usr/share/appdata/art.taunoerik.tauno-monitor.appdata.xml ]

    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    override-build: |
      # Point icon to the correct location
      sed -i.bak -e 's|Icon=art.taunoerik.tauno-monitor|Icon=/usr/share/icons/hicolor/scalable/apps/art.taunoerik.tauno-monitor.svg|g' $CRAFT_PART_SRC/data/art.taunoerik.tauno-monitor.desktop.in

      craftctl default
      pip3 install --target=$SNAPCRAFT_PART_INSTALL/ pyserial
      chmod +x $CRAFT_PART_INSTALL/usr/bin/tauno-monitor
      sed -i -e 's|/snap/gnome-42-2204-sdk/current/usr/bin/python3|/usr/bin/env python3|g' usr/bin/tauno-monitor
