#https://forum.snapcraft.io/t/snap-and-gtk4-sdk/37831/4
name: taunomonitor
base: core22
version: '0.1.13'
summary: Simple serial port monitor
description: |
  Simple  serial port monitor for the GNOME desktop.

grade: stable
confinement: strict

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

slots:
  # for GtkApplication registration
  taunomonitor:
    interface: dbus
    bus: session
    name: art.taunoerik.taunomonitor

apps:
  taunomonitor:
    extensions: [ gnome ]
    command: usr/bin/taunomonitor
    desktop: usr/share/applications/art.taunoerik.taunomonitor.desktop
    common-id: art.taunoerik.taunomonitor
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3.10/dist-packages:$SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages
    plugs:
      #- home
      #- desktop
      - raw-usb
      - serial-port
      - hardware-observe
      #- removable-media


layout:
  /usr/share/taunomonitor:
    bind: $SNAP/usr/share/taunomonitor

parts:
  taunomonitor:
    plugin: meson
    source: .
    parse-info: [ usr/share/metainfo/art.taunoerik.taunomonitor.metainfo.xml ]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    override-build: |
      # Point icon to the correct location
      sed -i.bak -e 's|Icon=art.taunoerik.taunomonitor|Icon=/usr/share/icons/hicolor/scalable/apps/art.taunoerik.taunomonitor.svg|g' $CRAFT_PART_SRC/data/art.taunoerik.taunomonitor.desktop.in

      craftctl default

      sed -i -e 's|/snap/gnome-42-2204-sdk/current/usr/bin/python3|/usr/bin/env python3|g' $CRAFT_PART_INSTALL/usr/bin/taunomonitor

      chmod +x $CRAFT_PART_INSTALL/usr/bin/taunomonitor
  pyserial:
    plugin: python
    source: .
    after: [taunomonitor]
    python-packages:
      - pyserial
